language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    fast_finish: true

before_script:
    - composer install --prefer-source

script: phpunit --coverage-text

notifications:
  email: false
